// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import AlertController from "./alert_controller.js"
application.register("alert", AlertController)

import DropdownController from "./dropdown_controller.js"
application.register("dropdown", DropdownController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import ModalController from "./modal_controller.js"
application.register("modal", ModalController)

import PopoverController from "./popover_controller.js"
application.register("popover", PopoverController)

import TabController from "./tab_controller.js"
application.register("tab", TabController)

import ToggleController from "./toggle_controller.js"
application.register("toggle", ToggleController)
