require: rubocop-rails

AllCops:
  NewCops: enable

Layout/LineLength:
  Exclude:
    - config/initializers/devise.rb

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false
